language: php
php:
- 5.5
- 5.6
- hhvm
sudo: false
before_install:
- composer self-update
install:
- travis_retry composer install --no-interaction --prefer-source
script:
- bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit; fi;'
- bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --coverage-clover
  build/logs/clover.xml; fi;'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7d93719c77ffe3ce57d1
    on_success: change
    on_failure: change
    on_start: false
  slack:
    secure: MT1miX0dpLZKrcY9iwukH+mez3oZgChiHduoMJARI7XMuAMVseMO+36ThE0UnP96sG1h/jxg3LgP/5/xL2eeD3+FiuX7dgVTg3KAP9ExuBxpKQemgoSD5Z+7GGsuBm35bHmQQedYY8V5Io38wsoe+LsYP9yugOTlpygjBrcoreM=
